module vcomp

fn resolve_syscall(sys Syscall) !int {
	match sys {
		int {
			return sys
		}
		string {
			$if amd64 {
				match sys {
					'read' { return 0 }
					'write' { return 1 }
					'open' { return 2 }
					'close' { return 3 }
					'stat' { return 4 }
					'fstat' { return 5 }
					'lstat' { return 6 }
					'poll' { return 7 }
					'lseek' { return 8 }
					'mmap' { return 9 }
					'mprotect' { return 10 }
					'munmap' { return 11 }
					'brk' { return 12 }
					'rt_sigaction' { return 13 }
					'rt_sigprocmask' { return 14 }
					'rt_sigreturn' { return 15 }
					'ioctl' { return 16 }
					'pread64' { return 17 }
					'pwrite64' { return 18 }
					'readv' { return 19 }
					'writev' { return 20 }
					'access' { return 21 }
					'pipe' { return 22 }
					'select' { return 23 }
					'sched_yield' { return 24 }
					'mremap' { return 25 }
					'msync' { return 26 }
					'mincore' { return 27 }
					'madvise' { return 28 }
					'shmget' { return 29 }
					'shmat' { return 30 }
					'shmctl' { return 31 }
					'dup' { return 32 }
					'dup2' { return 33 }
					'pause' { return 34 }
					'nanosleep' { return 35 }
					'getitimer' { return 36 }
					'alarm' { return 37 }
					'setitimer' { return 38 }
					'getpid' { return 39 }
					'sendfile' { return 40 }
					'socket' { return 41 }
					'connect' { return 42 }
					'accept' { return 43 }
					'sendto' { return 44 }
					'recvfrom' { return 45 }
					'sendmsg' { return 46 }
					'recvmsg' { return 47 }
					'shutdown' { return 48 }
					'bind' { return 49 }
					'listen' { return 50 }
					'getsockname' { return 51 }
					'getpeername' { return 52 }
					'socketpair' { return 53 }
					'setsockopt' { return 54 }
					'getsockopt' { return 55 }
					'clone' { return 56 }
					'fork' { return 57 }
					'vfork' { return 58 }
					'execve' { return 59 }
					'exit' { return 60 }
					'wait4' { return 61 }
					'kill' { return 62 }
					'uname' { return 63 }
					'semget' { return 64 }
					'semop' { return 65 }
					'semctl' { return 66 }
					'shmdt' { return 67 }
					'msgget' { return 68 }
					'msgsnd' { return 69 }
					'msgrcv' { return 70 }
					'msgctl' { return 71 }
					'fcntl' { return 72 }
					'flock' { return 73 }
					'fsync' { return 74 }
					'fdatasync' { return 75 }
					'truncate' { return 76 }
					'ftruncate' { return 77 }
					'getdents' { return 78 }
					'getcwd' { return 79 }
					'chdir' { return 80 }
					'fchdir' { return 81 }
					'rename' { return 82 }
					'mkdir' { return 83 }
					'rmdir' { return 84 }
					'creat' { return 85 }
					'link' { return 86 }
					'unlink' { return 87 }
					'symlink' { return 88 }
					'readlink' { return 89 }
					'chmod' { return 90 }
					'fchmod' { return 91 }
					'chown' { return 92 }
					'fchown' { return 93 }
					'lchown' { return 94 }
					'umask' { return 95 }
					'gettimeofday' { return 96 }
					'getrlimit' { return 97 }
					'getrusage' { return 98 }
					'sysinfo' { return 99 }
					'times' { return 100 }
					'ptrace' { return 101 }
					'getuid' { return 102 }
					'syslog' { return 103 }
					'getgid' { return 104 }
					'setuid' { return 105 }
					'setgid' { return 106 }
					'geteuid' { return 107 }
					'getegid' { return 108 }
					'setpgid' { return 109 }
					'getppid' { return 110 }
					'getpgrp' { return 111 }
					'setsid' { return 112 }
					'setreuid' { return 113 }
					'setregid' { return 114 }
					'getgroups' { return 115 }
					'setgroups' { return 116 }
					'setresuid' { return 117 }
					'getresuid' { return 118 }
					'setresgid' { return 119 }
					'getresgid' { return 120 }
					'getpgid' { return 121 }
					'setfsuid' { return 122 }
					'setfsgid' { return 123 }
					'getsid' { return 124 }
					'capget' { return 125 }
					'capset' { return 126 }
					'rt_sigpending' { return 127 }
					'rt_sigtimedwait' { return 128 }
					'rt_sigqueueinfo' { return 129 }
					'rt_sigsuspend' { return 130 }
					'sigaltstack' { return 131 }
					'utime' { return 132 }
					'mknod' { return 133 }
					'uselib' { return 134 }
					'personality' { return 135 }
					'ustat' { return 136 }
					'statfs' { return 137 }
					'fstatfs' { return 138 }
					'sysfs' { return 139 }
					'getpriority' { return 140 }
					'setpriority' { return 141 }
					'sched_setparam' { return 142 }
					'sched_getparam' { return 143 }
					'sched_setscheduler' { return 144 }
					'sched_getscheduler' { return 145 }
					'sched_get_priority_max' { return 146 }
					'sched_get_priority_min' { return 147 }
					'sched_rr_get_interval' { return 148 }
					'mlock' { return 149 }
					'munlock' { return 150 }
					'mlockall' { return 151 }
					'munlockall' { return 152 }
					'vhangup' { return 153 }
					'modify_ldt' { return 154 }
					'pivot_root' { return 155 }
					'_sysctl' { return 156 }
					'prctl' { return 157 }
					'arch_prctl' { return 158 }
					'adjtimex' { return 159 }
					'setrlimit' { return 160 }
					'chroot' { return 161 }
					'sync' { return 162 }
					'acct' { return 163 }
					'settimeofday' { return 164 }
					'mount' { return 165 }
					'umount2' { return 166 }
					'swapon' { return 167 }
					'swapoff' { return 168 }
					'reboot' { return 169 }
					'sethostname' { return 170 }
					'setdomainname' { return 171 }
					'iopl' { return 172 }
					'ioperm' { return 173 }
					'create_module' { return 174 }
					'init_module' { return 175 }
					'delete_module' { return 176 }
					'get_kernel_syms' { return 177 }
					'query_module' { return 178 }
					'quotactl' { return 179 }
					'nfsservctl' { return 180 }
					'getpmsg' { return 181 }
					'putpmsg' { return 182 }
					'afs_syscall' { return 183 }
					'tuxcall' { return 184 }
					'security' { return 185 }
					'gettid' { return 186 }
					'readahead' { return 187 }
					'setxattr' { return 188 }
					'lsetxattr' { return 189 }
					'fsetxattr' { return 190 }
					'getxattr' { return 191 }
					'lgetxattr' { return 192 }
					'fgetxattr' { return 193 }
					'listxattr' { return 194 }
					'llistxattr' { return 195 }
					'flistxattr' { return 196 }
					'removexattr' { return 197 }
					'lremovexattr' { return 198 }
					'fremovexattr' { return 199 }
					'tkill' { return 200 }
					'time' { return 201 }
					'futex' { return 202 }
					'sched_setaffinity' { return 203 }
					'sched_getaffinity' { return 204 }
					'set_thread_area' { return 205 }
					'io_setup' { return 206 }
					'io_destroy' { return 207 }
					'io_getevents' { return 208 }
					'io_submit' { return 209 }
					'io_cancel' { return 210 }
					'get_thread_area' { return 211 }
					'lookup_dcookie' { return 212 }
					'epoll_create' { return 213 }
					'epoll_ctl_old' { return 214 }
					'epoll_wait_old' { return 215 }
					'remap_file_pages' { return 216 }
					'getdents64' { return 217 }
					'set_tid_address' { return 218 }
					'restart_syscall' { return 219 }
					'semtimedop' { return 220 }
					'fadvise64' { return 221 }
					'timer_create' { return 222 }
					'timer_settime' { return 223 }
					'timer_gettime' { return 224 }
					'timer_getoverrun' { return 225 }
					'timer_delete' { return 226 }
					'clock_settime' { return 227 }
					'clock_gettime' { return 228 }
					'clock_getres' { return 229 }
					'clock_nanosleep' { return 230 }
					'exit_group' { return 231 }
					'epoll_wait' { return 232 }
					'epoll_ctl' { return 233 }
					'tgkill' { return 234 }
					'utimes' { return 235 }
					'vserver' { return 236 }
					'mbind' { return 237 }
					'set_mempolicy' { return 238 }
					'get_mempolicy' { return 239 }
					'mq_open' { return 240 }
					'mq_unlink' { return 241 }
					'mq_timedsend' { return 242 }
					'mq_timedreceive' { return 243 }
					'mq_notify' { return 244 }
					'mq_getsetattr' { return 245 }
					'kexec_load' { return 246 }
					'waitid' { return 247 }
					'add_key' { return 248 }
					'request_key' { return 249 }
					'keyctl' { return 250 }
					'ioprio_set' { return 251 }
					'ioprio_get' { return 252 }
					'inotify_init' { return 253 }
					'inotify_add_watch' { return 254 }
					'inotify_rm_watch' { return 255 }
					'migrate_pages' { return 256 }
					'openat' { return 257 }
					'mkdirat' { return 258 }
					'mknodat' { return 259 }
					'fchownat' { return 260 }
					'futimesat' { return 261 }
					'newfstatat' { return 262 }
					'unlinkat' { return 263 }
					'renameat' { return 264 }
					'linkat' { return 265 }
					'symlinkat' { return 266 }
					'readlinkat' { return 267 }
					'fchmodat' { return 268 }
					'faccessat' { return 269 }
					'pselect6' { return 270 }
					'ppoll' { return 271 }
					'unshare' { return 272 }
					'set_robust_list' { return 273 }
					'get_robust_list' { return 274 }
					'splice' { return 275 }
					'tee' { return 276 }
					'sync_file_range' { return 277 }
					'vmsplice' { return 278 }
					'move_pages' { return 279 }
					'utimensat' { return 280 }
					'epoll_pwait' { return 281 }
					'signalfd' { return 282 }
					'timerfd_create' { return 283 }
					'eventfd' { return 284 }
					'fallocate' { return 285 }
					'timerfd_settime' { return 286 }
					'timerfd_gettime' { return 287 }
					'accept4' { return 288 }
					'signalfd4' { return 289 }
					'eventfd2' { return 290 }
					'epoll_create1' { return 291 }
					'dup3' { return 292 }
					'pipe2' { return 293 }
					'inotify_init1' { return 294 }
					'preadv' { return 295 }
					'pwritev' { return 296 }
					'rt_tgsigqueueinfo' { return 297 }
					'perf_event_open' { return 298 }
					'recvmmsg' { return 299 }
					'fanotify_init' { return 300 }
					'fanotify_mark' { return 301 }
					'prlimit64' { return 302 }
					'name_to_handle_at' { return 303 }
					'open_by_handle_at' { return 304 }
					'clock_adjtime' { return 305 }
					'syncfs' { return 306 }
					'sendmmsg' { return 307 }
					'setns' { return 308 }
					'getcpu' { return 309 }
					'process_vm_readv' { return 310 }
					'process_vm_writev' { return 311 }
					'kcmp' { return 312 }
					'finit_module' { return 313 }
					'sched_setattr' { return 314 }
					'sched_getattr' { return 315 }
					'renameat2' { return 316 }
					'seccomp' { return 317 }
					'getrandom' { return 318 }
					'memfd_create' { return 319 }
					'kexec_file_load' { return 320 }
					'bpf' { return 321 }
					'execveat' { return 322 }
					'userfaultfd' { return 323 }
					'membarrier' { return 324 }
					'mlock2' { return 325 }
					'copy_file_range' { return 326 }
					'preadv2' { return 327 }
					'pwritev2' { return 328 }
					'pkey_mprotect' { return 329 }
					'pkey_alloc' { return 330 }
					'pkey_free' { return 331 }
					'statx' { return 332 }
					'io_pgetevents' { return 333 }
					'rseq' { return 334 }
					'uretprobe' { return 335 }
					'uprobe' { return 336 }
					'pidfd_send_signal' { return 424 }
					'io_uring_setup' { return 425 }
					'io_uring_enter' { return 426 }
					'io_uring_register' { return 427 }
					'open_tree' { return 428 }
					'move_mount' { return 429 }
					'fsopen' { return 430 }
					'fsconfig' { return 431 }
					'fsmount' { return 432 }
					'fspick' { return 433 }
					'pidfd_open' { return 434 }
					'clone3' { return 435 }
					'close_range' { return 436 }
					'openat2' { return 437 }
					'pidfd_getfd' { return 438 }
					'faccessat2' { return 439 }
					'process_madvise' { return 440 }
					'epoll_pwait2' { return 441 }
					'mount_setattr' { return 442 }
					'quotactl_fd' { return 443 }
					'landlock_create_ruleset' { return 444 }
					'landlock_add_rule' { return 445 }
					'landlock_restrict_self' { return 446 }
					'memfd_secret' { return 447 }
					'process_mrelease' { return 448 }
					'futex_waitv' { return 449 }
					'set_mempolicy_home_node' { return 450 }
					'cachestat' { return 451 }
					'fchmodat2' { return 452 }
					'map_shadow_stack' { return 453 }
					'futex_wake' { return 454 }
					'futex_wait' { return 455 }
					'futex_requeue' { return 456 }
					'statmount' { return 457 }
					'listmount' { return 458 }
					'lsm_get_self_attr' { return 459 }
					'lsm_set_self_attr' { return 460 }
					'lsm_list_modules' { return 461 }
					'mseal' { return 462 }
					'setxattrat' { return 463 }
					'getxattrat' { return 464 }
					'listxattrat' { return 465 }
					'removexattrat' { return 466 }
					'open_tree_attr' { return 467 }
					'file_getattr' { return 468 }
					'file_setattr' { return 469 }
					'listns' { return 470 }
					'rseq_slice_yield' { return 471 }
					else { return error('syscall "' + sys + '" is not supported on this architecture') }
				}
			} $else $if i386 {
				match sys {
					'restart_syscall' { return 0 }
					'exit' { return 1 }
					'fork' { return 2 }
					'read' { return 3 }
					'write' { return 4 }
					'open' { return 5 }
					'close' { return 6 }
					'waitpid' { return 7 }
					'creat' { return 8 }
					'link' { return 9 }
					'unlink' { return 10 }
					'execve' { return 11 }
					'chdir' { return 12 }
					'time' { return 13 }
					'mknod' { return 14 }
					'chmod' { return 15 }
					'lchown' { return 16 }
					'break' { return 17 }
					'oldstat' { return 18 }
					'lseek' { return 19 }
					'getpid' { return 20 }
					'mount' { return 21 }
					'umount' { return 22 }
					'setuid' { return 23 }
					'getuid' { return 24 }
					'stime' { return 25 }
					'ptrace' { return 26 }
					'alarm' { return 27 }
					'oldfstat' { return 28 }
					'pause' { return 29 }
					'utime' { return 30 }
					'stty' { return 31 }
					'gtty' { return 32 }
					'access' { return 33 }
					'nice' { return 34 }
					'ftime' { return 35 }
					'sync' { return 36 }
					'kill' { return 37 }
					'rename' { return 38 }
					'mkdir' { return 39 }
					'rmdir' { return 40 }
					'dup' { return 41 }
					'pipe' { return 42 }
					'times' { return 43 }
					'prof' { return 44 }
					'brk' { return 45 }
					'setgid' { return 46 }
					'getgid' { return 47 }
					'signal' { return 48 }
					'geteuid' { return 49 }
					'getegid' { return 50 }
					'acct' { return 51 }
					'umount2' { return 52 }
					'lock' { return 53 }
					'ioctl' { return 54 }
					'fcntl' { return 55 }
					'mpx' { return 56 }
					'setpgid' { return 57 }
					'ulimit' { return 58 }
					'oldolduname' { return 59 }
					'umask' { return 60 }
					'chroot' { return 61 }
					'ustat' { return 62 }
					'dup2' { return 63 }
					'getppid' { return 64 }
					'getpgrp' { return 65 }
					'setsid' { return 66 }
					'sigaction' { return 67 }
					'sgetmask' { return 68 }
					'ssetmask' { return 69 }
					'setreuid' { return 70 }
					'setregid' { return 71 }
					'sigsuspend' { return 72 }
					'sigpending' { return 73 }
					'sethostname' { return 74 }
					'setrlimit' { return 75 }
					'getrlimit' { return 76 }
					'getrusage' { return 77 }
					'gettimeofday' { return 78 }
					'settimeofday' { return 79 }
					'getgroups' { return 80 }
					'setgroups' { return 81 }
					'select' { return 82 }
					'symlink' { return 83 }
					'oldlstat' { return 84 }
					'readlink' { return 85 }
					'uselib' { return 86 }
					'swapon' { return 87 }
					'reboot' { return 88 }
					'readdir' { return 89 }
					'mmap' { return 90 }
					'munmap' { return 91 }
					'truncate' { return 92 }
					'ftruncate' { return 93 }
					'fchmod' { return 94 }
					'fchown' { return 95 }
					'getpriority' { return 96 }
					'setpriority' { return 97 }
					'profil' { return 98 }
					'statfs' { return 99 }
					'fstatfs' { return 100 }
					'ioperm' { return 101 }
					'socketcall' { return 102 }
					'syslog' { return 103 }
					'setitimer' { return 104 }
					'getitimer' { return 105 }
					'stat' { return 106 }
					'lstat' { return 107 }
					'fstat' { return 108 }
					'olduname' { return 109 }
					'iopl' { return 110 }
					'vhangup' { return 111 }
					'idle' { return 112 }
					'vm86old' { return 113 }
					'wait4' { return 114 }
					'swapoff' { return 115 }
					'sysinfo' { return 116 }
					'ipc' { return 117 }
					'fsync' { return 118 }
					'sigreturn' { return 119 }
					'clone' { return 120 }
					'setdomainname' { return 121 }
					'uname' { return 122 }
					'modify_ldt' { return 123 }
					'adjtimex' { return 124 }
					'mprotect' { return 125 }
					'sigprocmask' { return 126 }
					'create_module' { return 127 }
					'init_module' { return 128 }
					'delete_module' { return 129 }
					'get_kernel_syms' { return 130 }
					'quotactl' { return 131 }
					'getpgid' { return 132 }
					'fchdir' { return 133 }
					'bdflush' { return 134 }
					'sysfs' { return 135 }
					'personality' { return 136 }
					'afs_syscall' { return 137 }
					'setfsuid' { return 138 }
					'setfsgid' { return 139 }
					'_llseek' { return 140 }
					'getdents' { return 141 }
					'_newselect' { return 142 }
					'flock' { return 143 }
					'msync' { return 144 }
					'readv' { return 145 }
					'writev' { return 146 }
					'getsid' { return 147 }
					'fdatasync' { return 148 }
					'_sysctl' { return 149 }
					'mlock' { return 150 }
					'munlock' { return 151 }
					'mlockall' { return 152 }
					'munlockall' { return 153 }
					'sched_setparam' { return 154 }
					'sched_getparam' { return 155 }
					'sched_setscheduler' { return 156 }
					'sched_getscheduler' { return 157 }
					'sched_yield' { return 158 }
					'sched_get_priority_max' { return 159 }
					'sched_get_priority_min' { return 160 }
					'sched_rr_get_interval' { return 161 }
					'nanosleep' { return 162 }
					'mremap' { return 163 }
					'setresuid' { return 164 }
					'getresuid' { return 165 }
					'vm86' { return 166 }
					'query_module' { return 167 }
					'poll' { return 168 }
					'nfsservctl' { return 169 }
					'setresgid' { return 170 }
					'getresgid' { return 171 }
					'prctl' { return 172 }
					'rt_sigreturn' { return 173 }
					'rt_sigaction' { return 174 }
					'rt_sigprocmask' { return 175 }
					'rt_sigpending' { return 176 }
					'rt_sigtimedwait' { return 177 }
					'rt_sigqueueinfo' { return 178 }
					'rt_sigsuspend' { return 179 }
					'pread64' { return 180 }
					'pwrite64' { return 181 }
					'chown' { return 182 }
					'getcwd' { return 183 }
					'capget' { return 184 }
					'capset' { return 185 }
					'sigaltstack' { return 186 }
					'sendfile' { return 187 }
					'getpmsg' { return 188 }
					'putpmsg' { return 189 }
					'vfork' { return 190 }
					'ugetrlimit' { return 191 }
					'mmap2' { return 192 }
					'truncate64' { return 193 }
					'ftruncate64' { return 194 }
					'stat64' { return 195 }
					'lstat64' { return 196 }
					'fstat64' { return 197 }
					'lchown32' { return 198 }
					'getuid32' { return 199 }
					'getgid32' { return 200 }
					'geteuid32' { return 201 }
					'getegid32' { return 202 }
					'setreuid32' { return 203 }
					'setregid32' { return 204 }
					'getgroups32' { return 205 }
					'setgroups32' { return 206 }
					'fchown32' { return 207 }
					'setresuid32' { return 208 }
					'getresuid32' { return 209 }
					'setresgid32' { return 210 }
					'getresgid32' { return 211 }
					'chown32' { return 212 }
					'setuid32' { return 213 }
					'setgid32' { return 214 }
					'setfsuid32' { return 215 }
					'setfsgid32' { return 216 }
					'pivot_root' { return 217 }
					'mincore' { return 218 }
					'madvise' { return 219 }
					'getdents64' { return 220 }
					'fcntl64' { return 221 }
					'gettid' { return 224 }
					'readahead' { return 225 }
					'setxattr' { return 226 }
					'lsetxattr' { return 227 }
					'fsetxattr' { return 228 }
					'getxattr' { return 229 }
					'lgetxattr' { return 230 }
					'fgetxattr' { return 231 }
					'listxattr' { return 232 }
					'llistxattr' { return 233 }
					'flistxattr' { return 234 }
					'removexattr' { return 235 }
					'lremovexattr' { return 236 }
					'fremovexattr' { return 237 }
					'tkill' { return 238 }
					'sendfile64' { return 239 }
					'futex' { return 240 }
					'sched_setaffinity' { return 241 }
					'sched_getaffinity' { return 242 }
					'set_thread_area' { return 243 }
					'get_thread_area' { return 244 }
					'io_setup' { return 245 }
					'io_destroy' { return 246 }
					'io_getevents' { return 247 }
					'io_submit' { return 248 }
					'io_cancel' { return 249 }
					'fadvise64' { return 250 }
					'exit_group' { return 252 }
					'lookup_dcookie' { return 253 }
					'epoll_create' { return 254 }
					'epoll_ctl' { return 255 }
					'epoll_wait' { return 256 }
					'remap_file_pages' { return 257 }
					'set_tid_address' { return 258 }
					'timer_create' { return 259 }
					'timer_settime' { return 260 }
					'timer_gettime' { return 261 }
					'timer_getoverrun' { return 262 }
					'timer_delete' { return 263 }
					'clock_settime' { return 264 }
					'clock_gettime' { return 265 }
					'clock_getres' { return 266 }
					'clock_nanosleep' { return 267 }
					'statfs64' { return 268 }
					'fstatfs64' { return 269 }
					'tgkill' { return 270 }
					'utimes' { return 271 }
					'fadvise64_64' { return 272 }
					'vserver' { return 273 }
					'mbind' { return 274 }
					'get_mempolicy' { return 275 }
					'set_mempolicy' { return 276 }
					'mq_open' { return 277 }
					'mq_unlink' { return 278 }
					'mq_timedsend' { return 279 }
					'mq_timedreceive' { return 280 }
					'mq_notify' { return 281 }
					'mq_getsetattr' { return 282 }
					'kexec_load' { return 283 }
					'waitid' { return 284 }
					'add_key' { return 286 }
					'request_key' { return 287 }
					'keyctl' { return 288 }
					'ioprio_set' { return 289 }
					'ioprio_get' { return 290 }
					'inotify_init' { return 291 }
					'inotify_add_watch' { return 292 }
					'inotify_rm_watch' { return 293 }
					'migrate_pages' { return 294 }
					'openat' { return 295 }
					'mkdirat' { return 296 }
					'mknodat' { return 297 }
					'fchownat' { return 298 }
					'futimesat' { return 299 }
					'fstatat64' { return 300 }
					'unlinkat' { return 301 }
					'renameat' { return 302 }
					'linkat' { return 303 }
					'symlinkat' { return 304 }
					'readlinkat' { return 305 }
					'fchmodat' { return 306 }
					'faccessat' { return 307 }
					'pselect6' { return 308 }
					'ppoll' { return 309 }
					'unshare' { return 310 }
					'set_robust_list' { return 311 }
					'get_robust_list' { return 312 }
					'splice' { return 313 }
					'sync_file_range' { return 314 }
					'tee' { return 315 }
					'vmsplice' { return 316 }
					'move_pages' { return 317 }
					'getcpu' { return 318 }
					'epoll_pwait' { return 319 }
					'utimensat' { return 320 }
					'signalfd' { return 321 }
					'timerfd_create' { return 322 }
					'eventfd' { return 323 }
					'fallocate' { return 324 }
					'timerfd_settime' { return 325 }
					'timerfd_gettime' { return 326 }
					'signalfd4' { return 327 }
					'eventfd2' { return 328 }
					'epoll_create1' { return 329 }
					'dup3' { return 330 }
					'pipe2' { return 331 }
					'inotify_init1' { return 332 }
					'preadv' { return 333 }
					'pwritev' { return 334 }
					'rt_tgsigqueueinfo' { return 335 }
					'perf_event_open' { return 336 }
					'recvmmsg' { return 337 }
					'fanotify_init' { return 338 }
					'fanotify_mark' { return 339 }
					'prlimit64' { return 340 }
					'name_to_handle_at' { return 341 }
					'open_by_handle_at' { return 342 }
					'clock_adjtime' { return 343 }
					'syncfs' { return 344 }
					'sendmmsg' { return 345 }
					'setns' { return 346 }
					'process_vm_readv' { return 347 }
					'process_vm_writev' { return 348 }
					'kcmp' { return 349 }
					'finit_module' { return 350 }
					'sched_setattr' { return 351 }
					'sched_getattr' { return 352 }
					'renameat2' { return 353 }
					'seccomp' { return 354 }
					'getrandom' { return 355 }
					'memfd_create' { return 356 }
					'bpf' { return 357 }
					'execveat' { return 358 }
					'socket' { return 359 }
					'socketpair' { return 360 }
					'bind' { return 361 }
					'connect' { return 362 }
					'listen' { return 363 }
					'accept4' { return 364 }
					'getsockopt' { return 365 }
					'setsockopt' { return 366 }
					'getsockname' { return 367 }
					'getpeername' { return 368 }
					'sendto' { return 369 }
					'sendmsg' { return 370 }
					'recvfrom' { return 371 }
					'recvmsg' { return 372 }
					'shutdown' { return 373 }
					'userfaultfd' { return 374 }
					'membarrier' { return 375 }
					'mlock2' { return 376 }
					'copy_file_range' { return 377 }
					'preadv2' { return 378 }
					'pwritev2' { return 379 }
					'pkey_mprotect' { return 380 }
					'pkey_alloc' { return 381 }
					'pkey_free' { return 382 }
					'statx' { return 383 }
					'arch_prctl' { return 384 }
					'io_pgetevents' { return 385 }
					'rseq' { return 386 }
					'semget' { return 393 }
					'semctl' { return 394 }
					'shmget' { return 395 }
					'shmctl' { return 396 }
					'shmat' { return 397 }
					'shmdt' { return 398 }
					'msgget' { return 399 }
					'msgsnd' { return 400 }
					'msgrcv' { return 401 }
					'msgctl' { return 402 }
					'clock_gettime64' { return 403 }
					'clock_settime64' { return 404 }
					'clock_adjtime64' { return 405 }
					'clock_getres_time64' { return 406 }
					'clock_nanosleep_time64' { return 407 }
					'timer_gettime64' { return 408 }
					'timer_settime64' { return 409 }
					'timerfd_gettime64' { return 410 }
					'timerfd_settime64' { return 411 }
					'utimensat_time64' { return 412 }
					'pselect6_time64' { return 413 }
					'ppoll_time64' { return 414 }
					'io_pgetevents_time64' { return 416 }
					'recvmmsg_time64' { return 417 }
					'mq_timedsend_time64' { return 418 }
					'mq_timedreceive_time64' { return 419 }
					'semtimedop_time64' { return 420 }
					'rt_sigtimedwait_time64' { return 421 }
					'futex_time64' { return 422 }
					'sched_rr_get_interval_time64' { return 423 }
					'pidfd_send_signal' { return 424 }
					'io_uring_setup' { return 425 }
					'io_uring_enter' { return 426 }
					'io_uring_register' { return 427 }
					'open_tree' { return 428 }
					'move_mount' { return 429 }
					'fsopen' { return 430 }
					'fsconfig' { return 431 }
					'fsmount' { return 432 }
					'fspick' { return 433 }
					'pidfd_open' { return 434 }
					'clone3' { return 435 }
					'close_range' { return 436 }
					'openat2' { return 437 }
					'pidfd_getfd' { return 438 }
					'faccessat2' { return 439 }
					'process_madvise' { return 440 }
					'epoll_pwait2' { return 441 }
					'mount_setattr' { return 442 }
					'quotactl_fd' { return 443 }
					'landlock_create_ruleset' { return 444 }
					'landlock_add_rule' { return 445 }
					'landlock_restrict_self' { return 446 }
					'memfd_secret' { return 447 }
					'process_mrelease' { return 448 }
					'futex_waitv' { return 449 }
					'set_mempolicy_home_node' { return 450 }
					'cachestat' { return 451 }
					'fchmodat2' { return 452 }
					'map_shadow_stack' { return 453 }
					'futex_wake' { return 454 }
					'futex_wait' { return 455 }
					'futex_requeue' { return 456 }
					'statmount' { return 457 }
					'listmount' { return 458 }
					'lsm_get_self_attr' { return 459 }
					'lsm_set_self_attr' { return 460 }
					'lsm_list_modules' { return 461 }
					'mseal' { return 462 }
					'setxattrat' { return 463 }
					'getxattrat' { return 464 }
					'listxattrat' { return 465 }
					'removexattrat' { return 466 }
					'open_tree_attr' { return 467 }
					'file_getattr' { return 468 }
					'file_setattr' { return 469 }
					'listns' { return 470 }
					'rseq_slice_yield' { return 471 }
					else { return error('syscall "' + sys + '" is not supported on this architecture') }
				}
			} $else $if arm32 {
				match sys {
					'restart_syscall' { return 0 }
					'exit' { return 1 }
					'fork' { return 2 }
					'read' { return 3 }
					'write' { return 4 }
					'open' { return 5 }
					'close' { return 6 }
					'creat' { return 8 }
					'link' { return 9 }
					'unlink' { return 10 }
					'execve' { return 11 }
					'chdir' { return 12 }
					'time' { return 13 }
					'mknod' { return 14 }
					'chmod' { return 15 }
					'lchown' { return 16 }
					'lseek' { return 19 }
					'getpid' { return 20 }
					'mount' { return 21 }
					'umount' { return 22 }
					'setuid' { return 23 }
					'getuid' { return 24 }
					'stime' { return 25 }
					'ptrace' { return 26 }
					'alarm' { return 27 }
					'pause' { return 29 }
					'utime' { return 30 }
					'access' { return 33 }
					'nice' { return 34 }
					'sync' { return 36 }
					'kill' { return 37 }
					'rename' { return 38 }
					'mkdir' { return 39 }
					'rmdir' { return 40 }
					'dup' { return 41 }
					'pipe' { return 42 }
					'times' { return 43 }
					'brk' { return 45 }
					'setgid' { return 46 }
					'getgid' { return 47 }
					'geteuid' { return 49 }
					'getegid' { return 50 }
					'acct' { return 51 }
					'umount2' { return 52 }
					'ioctl' { return 54 }
					'fcntl' { return 55 }
					'setpgid' { return 57 }
					'umask' { return 60 }
					'chroot' { return 61 }
					'ustat' { return 62 }
					'dup2' { return 63 }
					'getppid' { return 64 }
					'getpgrp' { return 65 }
					'setsid' { return 66 }
					'sigaction' { return 67 }
					'setreuid' { return 70 }
					'setregid' { return 71 }
					'sigsuspend' { return 72 }
					'sigpending' { return 73 }
					'sethostname' { return 74 }
					'setrlimit' { return 75 }
					'getrlimit' { return 76 }
					'getrusage' { return 77 }
					'gettimeofday' { return 78 }
					'settimeofday' { return 79 }
					'getgroups' { return 80 }
					'setgroups' { return 81 }
					'select' { return 82 }
					'symlink' { return 83 }
					'readlink' { return 85 }
					'uselib' { return 86 }
					'swapon' { return 87 }
					'reboot' { return 88 }
					'readdir' { return 89 }
					'mmap' { return 90 }
					'munmap' { return 91 }
					'truncate' { return 92 }
					'ftruncate' { return 93 }
					'fchmod' { return 94 }
					'fchown' { return 95 }
					'getpriority' { return 96 }
					'setpriority' { return 97 }
					'statfs' { return 99 }
					'fstatfs' { return 100 }
					'socketcall' { return 102 }
					'syslog' { return 103 }
					'setitimer' { return 104 }
					'getitimer' { return 105 }
					'stat' { return 106 }
					'lstat' { return 107 }
					'fstat' { return 108 }
					'vhangup' { return 111 }
					'syscall' { return 113 }
					'wait4' { return 114 }
					'swapoff' { return 115 }
					'sysinfo' { return 116 }
					'ipc' { return 117 }
					'fsync' { return 118 }
					'sigreturn' { return 119 }
					'clone' { return 120 }
					'setdomainname' { return 121 }
					'uname' { return 122 }
					'adjtimex' { return 124 }
					'mprotect' { return 125 }
					'sigprocmask' { return 126 }
					'init_module' { return 128 }
					'delete_module' { return 129 }
					'quotactl' { return 131 }
					'getpgid' { return 132 }
					'fchdir' { return 133 }
					'bdflush' { return 134 }
					'sysfs' { return 135 }
					'personality' { return 136 }
					'setfsuid' { return 138 }
					'setfsgid' { return 139 }
					'_llseek' { return 140 }
					'getdents' { return 141 }
					'_newselect' { return 142 }
					'flock' { return 143 }
					'msync' { return 144 }
					'readv' { return 145 }
					'writev' { return 146 }
					'getsid' { return 147 }
					'fdatasync' { return 148 }
					'_sysctl' { return 149 }
					'mlock' { return 150 }
					'munlock' { return 151 }
					'mlockall' { return 152 }
					'munlockall' { return 153 }
					'sched_setparam' { return 154 }
					'sched_getparam' { return 155 }
					'sched_setscheduler' { return 156 }
					'sched_getscheduler' { return 157 }
					'sched_yield' { return 158 }
					'sched_get_priority_max' { return 159 }
					'sched_get_priority_min' { return 160 }
					'sched_rr_get_interval' { return 161 }
					'nanosleep' { return 162 }
					'mremap' { return 163 }
					'setresuid' { return 164 }
					'getresuid' { return 165 }
					'poll' { return 168 }
					'nfsservctl' { return 169 }
					'setresgid' { return 170 }
					'getresgid' { return 171 }
					'prctl' { return 172 }
					'rt_sigreturn' { return 173 }
					'rt_sigaction' { return 174 }
					'rt_sigprocmask' { return 175 }
					'rt_sigpending' { return 176 }
					'rt_sigtimedwait' { return 177 }
					'rt_sigqueueinfo' { return 178 }
					'rt_sigsuspend' { return 179 }
					'pread64' { return 180 }
					'pwrite64' { return 181 }
					'chown' { return 182 }
					'getcwd' { return 183 }
					'capget' { return 184 }
					'capset' { return 185 }
					'sigaltstack' { return 186 }
					'sendfile' { return 187 }
					'vfork' { return 190 }
					'ugetrlimit' { return 191 }
					'mmap2' { return 192 }
					'truncate64' { return 193 }
					'ftruncate64' { return 194 }
					'stat64' { return 195 }
					'lstat64' { return 196 }
					'fstat64' { return 197 }
					'lchown32' { return 198 }
					'getuid32' { return 199 }
					'getgid32' { return 200 }
					'geteuid32' { return 201 }
					'getegid32' { return 202 }
					'setreuid32' { return 203 }
					'setregid32' { return 204 }
					'getgroups32' { return 205 }
					'setgroups32' { return 206 }
					'fchown32' { return 207 }
					'setresuid32' { return 208 }
					'getresuid32' { return 209 }
					'setresgid32' { return 210 }
					'getresgid32' { return 211 }
					'chown32' { return 212 }
					'setuid32' { return 213 }
					'setgid32' { return 214 }
					'setfsuid32' { return 215 }
					'setfsgid32' { return 216 }
					'getdents64' { return 217 }
					'pivot_root' { return 218 }
					'mincore' { return 219 }
					'madvise' { return 220 }
					'fcntl64' { return 221 }
					'gettid' { return 224 }
					'readahead' { return 225 }
					'setxattr' { return 226 }
					'lsetxattr' { return 227 }
					'fsetxattr' { return 228 }
					'getxattr' { return 229 }
					'lgetxattr' { return 230 }
					'fgetxattr' { return 231 }
					'listxattr' { return 232 }
					'llistxattr' { return 233 }
					'flistxattr' { return 234 }
					'removexattr' { return 235 }
					'lremovexattr' { return 236 }
					'fremovexattr' { return 237 }
					'tkill' { return 238 }
					'sendfile64' { return 239 }
					'futex' { return 240 }
					'sched_setaffinity' { return 241 }
					'sched_getaffinity' { return 242 }
					'io_setup' { return 243 }
					'io_destroy' { return 244 }
					'io_getevents' { return 245 }
					'io_submit' { return 246 }
					'io_cancel' { return 247 }
					'exit_group' { return 248 }
					'lookup_dcookie' { return 249 }
					'epoll_create' { return 250 }
					'epoll_ctl' { return 251 }
					'epoll_wait' { return 252 }
					'remap_file_pages' { return 253 }
					'set_tid_address' { return 256 }
					'timer_create' { return 257 }
					'timer_settime' { return 258 }
					'timer_gettime' { return 259 }
					'timer_getoverrun' { return 260 }
					'timer_delete' { return 261 }
					'clock_settime' { return 262 }
					'clock_gettime' { return 263 }
					'clock_getres' { return 264 }
					'clock_nanosleep' { return 265 }
					'statfs64' { return 266 }
					'fstatfs64' { return 267 }
					'tgkill' { return 268 }
					'utimes' { return 269 }
					'arm_fadvise64_64' { return 270 }
					'pciconfig_iobase' { return 271 }
					'pciconfig_read' { return 272 }
					'pciconfig_write' { return 273 }
					'mq_open' { return 274 }
					'mq_unlink' { return 275 }
					'mq_timedsend' { return 276 }
					'mq_timedreceive' { return 277 }
					'mq_notify' { return 278 }
					'mq_getsetattr' { return 279 }
					'waitid' { return 280 }
					'socket' { return 281 }
					'bind' { return 282 }
					'connect' { return 283 }
					'listen' { return 284 }
					'accept' { return 285 }
					'getsockname' { return 286 }
					'getpeername' { return 287 }
					'socketpair' { return 288 }
					'send' { return 289 }
					'sendto' { return 290 }
					'recv' { return 291 }
					'recvfrom' { return 292 }
					'shutdown' { return 293 }
					'setsockopt' { return 294 }
					'getsockopt' { return 295 }
					'sendmsg' { return 296 }
					'recvmsg' { return 297 }
					'semop' { return 298 }
					'semget' { return 299 }
					'semctl' { return 300 }
					'msgsnd' { return 301 }
					'msgrcv' { return 302 }
					'msgget' { return 303 }
					'msgctl' { return 304 }
					'shmat' { return 305 }
					'shmdt' { return 306 }
					'shmget' { return 307 }
					'shmctl' { return 308 }
					'add_key' { return 309 }
					'request_key' { return 310 }
					'keyctl' { return 311 }
					'semtimedop' { return 312 }
					'vserver' { return 313 }
					'ioprio_set' { return 314 }
					'ioprio_get' { return 315 }
					'inotify_init' { return 316 }
					'inotify_add_watch' { return 317 }
					'inotify_rm_watch' { return 318 }
					'mbind' { return 319 }
					'get_mempolicy' { return 320 }
					'set_mempolicy' { return 321 }
					'openat' { return 322 }
					'mkdirat' { return 323 }
					'mknodat' { return 324 }
					'fchownat' { return 325 }
					'futimesat' { return 326 }
					'fstatat64' { return 327 }
					'unlinkat' { return 328 }
					'renameat' { return 329 }
					'linkat' { return 330 }
					'symlinkat' { return 331 }
					'readlinkat' { return 332 }
					'fchmodat' { return 333 }
					'faccessat' { return 334 }
					'pselect6' { return 335 }
					'ppoll' { return 336 }
					'unshare' { return 337 }
					'set_robust_list' { return 338 }
					'get_robust_list' { return 339 }
					'splice' { return 340 }
					'arm_sync_file_range' { return 341 }
					'tee' { return 342 }
					'vmsplice' { return 343 }
					'move_pages' { return 344 }
					'getcpu' { return 345 }
					'epoll_pwait' { return 346 }
					'kexec_load' { return 347 }
					'utimensat' { return 348 }
					'signalfd' { return 349 }
					'timerfd_create' { return 350 }
					'eventfd' { return 351 }
					'fallocate' { return 352 }
					'timerfd_settime' { return 353 }
					'timerfd_gettime' { return 354 }
					'signalfd4' { return 355 }
					'eventfd2' { return 356 }
					'epoll_create1' { return 357 }
					'dup3' { return 358 }
					'pipe2' { return 359 }
					'inotify_init1' { return 360 }
					'preadv' { return 361 }
					'pwritev' { return 362 }
					'rt_tgsigqueueinfo' { return 363 }
					'perf_event_open' { return 364 }
					'recvmmsg' { return 365 }
					'accept4' { return 366 }
					'fanotify_init' { return 367 }
					'fanotify_mark' { return 368 }
					'prlimit64' { return 369 }
					'name_to_handle_at' { return 370 }
					'open_by_handle_at' { return 371 }
					'clock_adjtime' { return 372 }
					'syncfs' { return 373 }
					'sendmmsg' { return 374 }
					'setns' { return 375 }
					'process_vm_readv' { return 376 }
					'process_vm_writev' { return 377 }
					'kcmp' { return 378 }
					'finit_module' { return 379 }
					'sched_setattr' { return 380 }
					'sched_getattr' { return 381 }
					'renameat2' { return 382 }
					'seccomp' { return 383 }
					'getrandom' { return 384 }
					'memfd_create' { return 385 }
					'bpf' { return 386 }
					'execveat' { return 387 }
					'userfaultfd' { return 388 }
					'membarrier' { return 389 }
					'mlock2' { return 390 }
					'copy_file_range' { return 391 }
					'preadv2' { return 392 }
					'pwritev2' { return 393 }
					'pkey_mprotect' { return 394 }
					'pkey_alloc' { return 395 }
					'pkey_free' { return 396 }
					'statx' { return 397 }
					'rseq' { return 398 }
					'io_pgetevents' { return 399 }
					'migrate_pages' { return 400 }
					'kexec_file_load' { return 401 }
					'clock_gettime64' { return 403 }
					'clock_settime64' { return 404 }
					'clock_adjtime64' { return 405 }
					'clock_getres_time64' { return 406 }
					'clock_nanosleep_time64' { return 407 }
					'timer_gettime64' { return 408 }
					'timer_settime64' { return 409 }
					'timerfd_gettime64' { return 410 }
					'timerfd_settime64' { return 411 }
					'utimensat_time64' { return 412 }
					'pselect6_time64' { return 413 }
					'ppoll_time64' { return 414 }
					'io_pgetevents_time64' { return 416 }
					'recvmmsg_time64' { return 417 }
					'mq_timedsend_time64' { return 418 }
					'mq_timedreceive_time64' { return 419 }
					'semtimedop_time64' { return 420 }
					'rt_sigtimedwait_time64' { return 421 }
					'futex_time64' { return 422 }
					'sched_rr_get_interval_time64' { return 423 }
					'pidfd_send_signal' { return 424 }
					'io_uring_setup' { return 425 }
					'io_uring_enter' { return 426 }
					'io_uring_register' { return 427 }
					'open_tree' { return 428 }
					'move_mount' { return 429 }
					'fsopen' { return 430 }
					'fsconfig' { return 431 }
					'fsmount' { return 432 }
					'fspick' { return 433 }
					'pidfd_open' { return 434 }
					'clone3' { return 435 }
					'close_range' { return 436 }
					'openat2' { return 437 }
					'pidfd_getfd' { return 438 }
					'faccessat2' { return 439 }
					'process_madvise' { return 440 }
					'epoll_pwait2' { return 441 }
					'mount_setattr' { return 442 }
					'quotactl_fd' { return 443 }
					'landlock_create_ruleset' { return 444 }
					'landlock_add_rule' { return 445 }
					'landlock_restrict_self' { return 446 }
					'process_mrelease' { return 448 }
					'futex_waitv' { return 449 }
					'set_mempolicy_home_node' { return 450 }
					'cachestat' { return 451 }
					'fchmodat2' { return 452 }
					'map_shadow_stack' { return 453 }
					'futex_wake' { return 454 }
					'futex_wait' { return 455 }
					'futex_requeue' { return 456 }
					'statmount' { return 457 }
					'listmount' { return 458 }
					'lsm_get_self_attr' { return 459 }
					'lsm_set_self_attr' { return 460 }
					'lsm_list_modules' { return 461 }
					'mseal' { return 462 }
					'setxattrat' { return 463 }
					'getxattrat' { return 464 }
					'listxattrat' { return 465 }
					'removexattrat' { return 466 }
					'open_tree_attr' { return 467 }
					'file_getattr' { return 468 }
					'file_setattr' { return 469 }
					'listns' { return 470 }
					'rseq_slice_yield' { return 471 }
					else { return error('syscall "' + sys + '" is not supported on this architecture') }
				}
			} $else $if arm64 {
				match sys {
					'io_setup' { return 0 }
					'io_destroy' { return 1 }
					'io_submit' { return 2 }
					'io_cancel' { return 3 }
					'io_getevents' { return 4 }
					'setxattr' { return 5 }
					'lsetxattr' { return 6 }
					'fsetxattr' { return 7 }
					'getxattr' { return 8 }
					'lgetxattr' { return 9 }
					'fgetxattr' { return 10 }
					'listxattr' { return 11 }
					'llistxattr' { return 12 }
					'flistxattr' { return 13 }
					'removexattr' { return 14 }
					'lremovexattr' { return 15 }
					'fremovexattr' { return 16 }
					'getcwd' { return 17 }
					'lookup_dcookie' { return 18 }
					'eventfd2' { return 19 }
					'epoll_create1' { return 20 }
					'epoll_ctl' { return 21 }
					'epoll_pwait' { return 22 }
					'dup' { return 23 }
					'dup3' { return 24 }
					'inotify_init1' { return 26 }
					'inotify_add_watch' { return 27 }
					'inotify_rm_watch' { return 28 }
					'ioctl' { return 29 }
					'ioprio_set' { return 30 }
					'ioprio_get' { return 31 }
					'flock' { return 32 }
					'mknodat' { return 33 }
					'mkdirat' { return 34 }
					'unlinkat' { return 35 }
					'symlinkat' { return 36 }
					'linkat' { return 37 }
					'renameat' { return 38 }
					'umount2' { return 39 }
					'mount' { return 40 }
					'pivot_root' { return 41 }
					'nfsservctl' { return 42 }
					'fallocate' { return 47 }
					'faccessat' { return 48 }
					'chdir' { return 49 }
					'fchdir' { return 50 }
					'chroot' { return 51 }
					'fchmod' { return 52 }
					'fchmodat' { return 53 }
					'fchownat' { return 54 }
					'fchown' { return 55 }
					'openat' { return 56 }
					'close' { return 57 }
					'vhangup' { return 58 }
					'pipe2' { return 59 }
					'quotactl' { return 60 }
					'getdents64' { return 61 }
					'read' { return 63 }
					'write' { return 64 }
					'readv' { return 65 }
					'writev' { return 66 }
					'pread64' { return 67 }
					'pwrite64' { return 68 }
					'preadv' { return 69 }
					'pwritev' { return 70 }
					'pselect6' { return 72 }
					'ppoll' { return 73 }
					'signalfd4' { return 74 }
					'vmsplice' { return 75 }
					'splice' { return 76 }
					'tee' { return 77 }
					'readlinkat' { return 78 }
					'sync' { return 81 }
					'fsync' { return 82 }
					'fdatasync' { return 83 }
					'sync_file_range2' { return 84 }
					'sync_file_range' { return 84 }
					'timerfd_create' { return 85 }
					'timerfd_settime' { return 86 }
					'timerfd_gettime' { return 87 }
					'utimensat' { return 88 }
					'acct' { return 89 }
					'capget' { return 90 }
					'capset' { return 91 }
					'personality' { return 92 }
					'exit' { return 93 }
					'exit_group' { return 94 }
					'waitid' { return 95 }
					'set_tid_address' { return 96 }
					'unshare' { return 97 }
					'futex' { return 98 }
					'set_robust_list' { return 99 }
					'get_robust_list' { return 100 }
					'nanosleep' { return 101 }
					'getitimer' { return 102 }
					'setitimer' { return 103 }
					'kexec_load' { return 104 }
					'init_module' { return 105 }
					'delete_module' { return 106 }
					'timer_create' { return 107 }
					'timer_gettime' { return 108 }
					'timer_getoverrun' { return 109 }
					'timer_settime' { return 110 }
					'timer_delete' { return 111 }
					'clock_settime' { return 112 }
					'clock_gettime' { return 113 }
					'clock_getres' { return 114 }
					'clock_nanosleep' { return 115 }
					'syslog' { return 116 }
					'ptrace' { return 117 }
					'sched_setparam' { return 118 }
					'sched_setscheduler' { return 119 }
					'sched_getscheduler' { return 120 }
					'sched_getparam' { return 121 }
					'sched_setaffinity' { return 122 }
					'sched_getaffinity' { return 123 }
					'sched_yield' { return 124 }
					'sched_get_priority_max' { return 125 }
					'sched_get_priority_min' { return 126 }
					'sched_rr_get_interval' { return 127 }
					'restart_syscall' { return 128 }
					'kill' { return 129 }
					'tkill' { return 130 }
					'tgkill' { return 131 }
					'sigaltstack' { return 132 }
					'rt_sigsuspend' { return 133 }
					'rt_sigaction' { return 134 }
					'rt_sigprocmask' { return 135 }
					'rt_sigpending' { return 136 }
					'rt_sigtimedwait' { return 137 }
					'rt_sigqueueinfo' { return 138 }
					'rt_sigreturn' { return 139 }
					'setpriority' { return 140 }
					'getpriority' { return 141 }
					'reboot' { return 142 }
					'setregid' { return 143 }
					'setgid' { return 144 }
					'setreuid' { return 145 }
					'setuid' { return 146 }
					'setresuid' { return 147 }
					'getresuid' { return 148 }
					'setresgid' { return 149 }
					'getresgid' { return 150 }
					'setfsuid' { return 151 }
					'setfsgid' { return 152 }
					'times' { return 153 }
					'setpgid' { return 154 }
					'getpgid' { return 155 }
					'getsid' { return 156 }
					'setsid' { return 157 }
					'getgroups' { return 158 }
					'setgroups' { return 159 }
					'uname' { return 160 }
					'sethostname' { return 161 }
					'setdomainname' { return 162 }
					'getrlimit' { return 163 }
					'setrlimit' { return 164 }
					'getrusage' { return 165 }
					'umask' { return 166 }
					'prctl' { return 167 }
					'getcpu' { return 168 }
					'gettimeofday' { return 169 }
					'settimeofday' { return 170 }
					'adjtimex' { return 171 }
					'getpid' { return 172 }
					'getppid' { return 173 }
					'getuid' { return 174 }
					'geteuid' { return 175 }
					'getgid' { return 176 }
					'getegid' { return 177 }
					'gettid' { return 178 }
					'sysinfo' { return 179 }
					'mq_open' { return 180 }
					'mq_unlink' { return 181 }
					'mq_timedsend' { return 182 }
					'mq_timedreceive' { return 183 }
					'mq_notify' { return 184 }
					'mq_getsetattr' { return 185 }
					'msgget' { return 186 }
					'msgctl' { return 187 }
					'msgrcv' { return 188 }
					'msgsnd' { return 189 }
					'semget' { return 190 }
					'semctl' { return 191 }
					'semtimedop' { return 192 }
					'semop' { return 193 }
					'shmget' { return 194 }
					'shmctl' { return 195 }
					'shmat' { return 196 }
					'shmdt' { return 197 }
					'socket' { return 198 }
					'socketpair' { return 199 }
					'bind' { return 200 }
					'listen' { return 201 }
					'accept' { return 202 }
					'connect' { return 203 }
					'getsockname' { return 204 }
					'getpeername' { return 205 }
					'sendto' { return 206 }
					'recvfrom' { return 207 }
					'setsockopt' { return 208 }
					'getsockopt' { return 209 }
					'shutdown' { return 210 }
					'sendmsg' { return 211 }
					'recvmsg' { return 212 }
					'readahead' { return 213 }
					'brk' { return 214 }
					'munmap' { return 215 }
					'mremap' { return 216 }
					'add_key' { return 217 }
					'request_key' { return 218 }
					'keyctl' { return 219 }
					'clone' { return 220 }
					'execve' { return 221 }
					'swapon' { return 224 }
					'swapoff' { return 225 }
					'mprotect' { return 226 }
					'msync' { return 227 }
					'mlock' { return 228 }
					'munlock' { return 229 }
					'mlockall' { return 230 }
					'munlockall' { return 231 }
					'mincore' { return 232 }
					'madvise' { return 233 }
					'remap_file_pages' { return 234 }
					'mbind' { return 235 }
					'get_mempolicy' { return 236 }
					'set_mempolicy' { return 237 }
					'migrate_pages' { return 238 }
					'move_pages' { return 239 }
					'rt_tgsigqueueinfo' { return 240 }
					'perf_event_open' { return 241 }
					'accept4' { return 242 }
					'recvmmsg' { return 243 }
					'arch_specific_syscall' { return 244 }
					'wait4' { return 260 }
					'prlimit64' { return 261 }
					'fanotify_init' { return 262 }
					'fanotify_mark' { return 263 }
					'name_to_handle_at' { return 264 }
					'open_by_handle_at' { return 265 }
					'clock_adjtime' { return 266 }
					'syncfs' { return 267 }
					'setns' { return 268 }
					'sendmmsg' { return 269 }
					'process_vm_readv' { return 270 }
					'process_vm_writev' { return 271 }
					'kcmp' { return 272 }
					'finit_module' { return 273 }
					'sched_setattr' { return 274 }
					'sched_getattr' { return 275 }
					'renameat2' { return 276 }
					'seccomp' { return 277 }
					'getrandom' { return 278 }
					'memfd_create' { return 279 }
					'bpf' { return 280 }
					'execveat' { return 281 }
					'userfaultfd' { return 282 }
					'membarrier' { return 283 }
					'mlock2' { return 284 }
					'copy_file_range' { return 285 }
					'preadv2' { return 286 }
					'pwritev2' { return 287 }
					'pkey_mprotect' { return 288 }
					'pkey_alloc' { return 289 }
					'pkey_free' { return 290 }
					'statx' { return 291 }
					'io_pgetevents' { return 292 }
					'rseq' { return 293 }
					'kexec_file_load' { return 294 }
					'clock_gettime64' { return 403 }
					'clock_settime64' { return 404 }
					'clock_adjtime64' { return 405 }
					'clock_getres_time64' { return 406 }
					'clock_nanosleep_time64' { return 407 }
					'timer_gettime64' { return 408 }
					'timer_settime64' { return 409 }
					'timerfd_gettime64' { return 410 }
					'timerfd_settime64' { return 411 }
					'utimensat_time64' { return 412 }
					'pselect6_time64' { return 413 }
					'ppoll_time64' { return 414 }
					'io_pgetevents_time64' { return 416 }
					'recvmmsg_time64' { return 417 }
					'mq_timedsend_time64' { return 418 }
					'mq_timedreceive_time64' { return 419 }
					'semtimedop_time64' { return 420 }
					'rt_sigtimedwait_time64' { return 421 }
					'futex_time64' { return 422 }
					'sched_rr_get_interval_time64' { return 423 }
					'pidfd_send_signal' { return 424 }
					'io_uring_setup' { return 425 }
					'io_uring_enter' { return 426 }
					'io_uring_register' { return 427 }
					'open_tree' { return 428 }
					'move_mount' { return 429 }
					'fsopen' { return 430 }
					'fsconfig' { return 431 }
					'fsmount' { return 432 }
					'fspick' { return 433 }
					'pidfd_open' { return 434 }
					'clone3' { return 435 }
					'close_range' { return 436 }
					'openat2' { return 437 }
					'pidfd_getfd' { return 438 }
					'faccessat2' { return 439 }
					'process_madvise' { return 440 }
					'epoll_pwait2' { return 441 }
					'mount_setattr' { return 442 }
					'quotactl_fd' { return 443 }
					'landlock_create_ruleset' { return 444 }
					'landlock_add_rule' { return 445 }
					'landlock_restrict_self' { return 446 }
					'memfd_secret' { return 447 }
					'process_mrelease' { return 448 }
					'futex_waitv' { return 449 }
					'set_mempolicy_home_node' { return 450 }
					'cachestat' { return 451 }
					'fchmodat2' { return 452 }
					'map_shadow_stack' { return 453 }
					'futex_wake' { return 454 }
					'futex_wait' { return 455 }
					'futex_requeue' { return 456 }
					'statmount' { return 457 }
					'listmount' { return 458 }
					'lsm_get_self_attr' { return 459 }
					'lsm_set_self_attr' { return 460 }
					'lsm_list_modules' { return 461 }
					'mseal' { return 462 }
					'setxattrat' { return 463 }
					'getxattrat' { return 464 }
					'listxattrat' { return 465 }
					'removexattrat' { return 466 }
					'open_tree_attr' { return 467 }
					'file_getattr' { return 468 }
					'file_setattr' { return 469 }
					'listns' { return 470 }
					'rseq_slice_yield' { return 471 }
					'syscalls' { return 472 }
					else { return error('syscall "' + sys + '" is not supported on this architecture') }
				}
			} $else $if rv64 {
				match sys {
					'io_setup' { return 0 }
					'io_destroy' { return 1 }
					'io_submit' { return 2 }
					'io_cancel' { return 3 }
					'io_getevents' { return 4 }
					'setxattr' { return 5 }
					'lsetxattr' { return 6 }
					'fsetxattr' { return 7 }
					'getxattr' { return 8 }
					'lgetxattr' { return 9 }
					'fgetxattr' { return 10 }
					'listxattr' { return 11 }
					'llistxattr' { return 12 }
					'flistxattr' { return 13 }
					'removexattr' { return 14 }
					'lremovexattr' { return 15 }
					'fremovexattr' { return 16 }
					'getcwd' { return 17 }
					'lookup_dcookie' { return 18 }
					'eventfd2' { return 19 }
					'epoll_create1' { return 20 }
					'epoll_ctl' { return 21 }
					'epoll_pwait' { return 22 }
					'dup' { return 23 }
					'dup3' { return 24 }
					'inotify_init1' { return 26 }
					'inotify_add_watch' { return 27 }
					'inotify_rm_watch' { return 28 }
					'ioctl' { return 29 }
					'ioprio_set' { return 30 }
					'ioprio_get' { return 31 }
					'flock' { return 32 }
					'mknodat' { return 33 }
					'mkdirat' { return 34 }
					'unlinkat' { return 35 }
					'symlinkat' { return 36 }
					'linkat' { return 37 }
					'renameat' { return 38 }
					'umount2' { return 39 }
					'mount' { return 40 }
					'pivot_root' { return 41 }
					'nfsservctl' { return 42 }
					'fallocate' { return 47 }
					'faccessat' { return 48 }
					'chdir' { return 49 }
					'fchdir' { return 50 }
					'chroot' { return 51 }
					'fchmod' { return 52 }
					'fchmodat' { return 53 }
					'fchownat' { return 54 }
					'fchown' { return 55 }
					'openat' { return 56 }
					'close' { return 57 }
					'vhangup' { return 58 }
					'pipe2' { return 59 }
					'quotactl' { return 60 }
					'getdents64' { return 61 }
					'read' { return 63 }
					'write' { return 64 }
					'readv' { return 65 }
					'writev' { return 66 }
					'pread64' { return 67 }
					'pwrite64' { return 68 }
					'preadv' { return 69 }
					'pwritev' { return 70 }
					'pselect6' { return 72 }
					'ppoll' { return 73 }
					'signalfd4' { return 74 }
					'vmsplice' { return 75 }
					'splice' { return 76 }
					'tee' { return 77 }
					'readlinkat' { return 78 }
					'sync' { return 81 }
					'fsync' { return 82 }
					'fdatasync' { return 83 }
					'sync_file_range2' { return 84 }
					'sync_file_range' { return 84 }
					'timerfd_create' { return 85 }
					'timerfd_settime' { return 86 }
					'timerfd_gettime' { return 87 }
					'utimensat' { return 88 }
					'acct' { return 89 }
					'capget' { return 90 }
					'capset' { return 91 }
					'personality' { return 92 }
					'exit' { return 93 }
					'exit_group' { return 94 }
					'waitid' { return 95 }
					'set_tid_address' { return 96 }
					'unshare' { return 97 }
					'futex' { return 98 }
					'set_robust_list' { return 99 }
					'get_robust_list' { return 100 }
					'nanosleep' { return 101 }
					'getitimer' { return 102 }
					'setitimer' { return 103 }
					'kexec_load' { return 104 }
					'init_module' { return 105 }
					'delete_module' { return 106 }
					'timer_create' { return 107 }
					'timer_gettime' { return 108 }
					'timer_getoverrun' { return 109 }
					'timer_settime' { return 110 }
					'timer_delete' { return 111 }
					'clock_settime' { return 112 }
					'clock_gettime' { return 113 }
					'clock_getres' { return 114 }
					'clock_nanosleep' { return 115 }
					'syslog' { return 116 }
					'ptrace' { return 117 }
					'sched_setparam' { return 118 }
					'sched_setscheduler' { return 119 }
					'sched_getscheduler' { return 120 }
					'sched_getparam' { return 121 }
					'sched_setaffinity' { return 122 }
					'sched_getaffinity' { return 123 }
					'sched_yield' { return 124 }
					'sched_get_priority_max' { return 125 }
					'sched_get_priority_min' { return 126 }
					'sched_rr_get_interval' { return 127 }
					'restart_syscall' { return 128 }
					'kill' { return 129 }
					'tkill' { return 130 }
					'tgkill' { return 131 }
					'sigaltstack' { return 132 }
					'rt_sigsuspend' { return 133 }
					'rt_sigaction' { return 134 }
					'rt_sigprocmask' { return 135 }
					'rt_sigpending' { return 136 }
					'rt_sigtimedwait' { return 137 }
					'rt_sigqueueinfo' { return 138 }
					'rt_sigreturn' { return 139 }
					'setpriority' { return 140 }
					'getpriority' { return 141 }
					'reboot' { return 142 }
					'setregid' { return 143 }
					'setgid' { return 144 }
					'setreuid' { return 145 }
					'setuid' { return 146 }
					'setresuid' { return 147 }
					'getresuid' { return 148 }
					'setresgid' { return 149 }
					'getresgid' { return 150 }
					'setfsuid' { return 151 }
					'setfsgid' { return 152 }
					'times' { return 153 }
					'setpgid' { return 154 }
					'getpgid' { return 155 }
					'getsid' { return 156 }
					'setsid' { return 157 }
					'getgroups' { return 158 }
					'setgroups' { return 159 }
					'uname' { return 160 }
					'sethostname' { return 161 }
					'setdomainname' { return 162 }
					'getrlimit' { return 163 }
					'setrlimit' { return 164 }
					'getrusage' { return 165 }
					'umask' { return 166 }
					'prctl' { return 167 }
					'getcpu' { return 168 }
					'gettimeofday' { return 169 }
					'settimeofday' { return 170 }
					'adjtimex' { return 171 }
					'getpid' { return 172 }
					'getppid' { return 173 }
					'getuid' { return 174 }
					'geteuid' { return 175 }
					'getgid' { return 176 }
					'getegid' { return 177 }
					'gettid' { return 178 }
					'sysinfo' { return 179 }
					'mq_open' { return 180 }
					'mq_unlink' { return 181 }
					'mq_timedsend' { return 182 }
					'mq_timedreceive' { return 183 }
					'mq_notify' { return 184 }
					'mq_getsetattr' { return 185 }
					'msgget' { return 186 }
					'msgctl' { return 187 }
					'msgrcv' { return 188 }
					'msgsnd' { return 189 }
					'semget' { return 190 }
					'semctl' { return 191 }
					'semtimedop' { return 192 }
					'semop' { return 193 }
					'shmget' { return 194 }
					'shmctl' { return 195 }
					'shmat' { return 196 }
					'shmdt' { return 197 }
					'socket' { return 198 }
					'socketpair' { return 199 }
					'bind' { return 200 }
					'listen' { return 201 }
					'accept' { return 202 }
					'connect' { return 203 }
					'getsockname' { return 204 }
					'getpeername' { return 205 }
					'sendto' { return 206 }
					'recvfrom' { return 207 }
					'setsockopt' { return 208 }
					'getsockopt' { return 209 }
					'shutdown' { return 210 }
					'sendmsg' { return 211 }
					'recvmsg' { return 212 }
					'readahead' { return 213 }
					'brk' { return 214 }
					'munmap' { return 215 }
					'mremap' { return 216 }
					'add_key' { return 217 }
					'request_key' { return 218 }
					'keyctl' { return 219 }
					'clone' { return 220 }
					'execve' { return 221 }
					'swapon' { return 224 }
					'swapoff' { return 225 }
					'mprotect' { return 226 }
					'msync' { return 227 }
					'mlock' { return 228 }
					'munlock' { return 229 }
					'mlockall' { return 230 }
					'munlockall' { return 231 }
					'mincore' { return 232 }
					'madvise' { return 233 }
					'remap_file_pages' { return 234 }
					'mbind' { return 235 }
					'get_mempolicy' { return 236 }
					'set_mempolicy' { return 237 }
					'migrate_pages' { return 238 }
					'move_pages' { return 239 }
					'rt_tgsigqueueinfo' { return 240 }
					'perf_event_open' { return 241 }
					'accept4' { return 242 }
					'recvmmsg' { return 243 }
					'arch_specific_syscall' { return 244 }
					'wait4' { return 260 }
					'prlimit64' { return 261 }
					'fanotify_init' { return 262 }
					'fanotify_mark' { return 263 }
					'name_to_handle_at' { return 264 }
					'open_by_handle_at' { return 265 }
					'clock_adjtime' { return 266 }
					'syncfs' { return 267 }
					'setns' { return 268 }
					'sendmmsg' { return 269 }
					'process_vm_readv' { return 270 }
					'process_vm_writev' { return 271 }
					'kcmp' { return 272 }
					'finit_module' { return 273 }
					'sched_setattr' { return 274 }
					'sched_getattr' { return 275 }
					'renameat2' { return 276 }
					'seccomp' { return 277 }
					'getrandom' { return 278 }
					'memfd_create' { return 279 }
					'bpf' { return 280 }
					'execveat' { return 281 }
					'userfaultfd' { return 282 }
					'membarrier' { return 283 }
					'mlock2' { return 284 }
					'copy_file_range' { return 285 }
					'preadv2' { return 286 }
					'pwritev2' { return 287 }
					'pkey_mprotect' { return 288 }
					'pkey_alloc' { return 289 }
					'pkey_free' { return 290 }
					'statx' { return 291 }
					'io_pgetevents' { return 292 }
					'rseq' { return 293 }
					'kexec_file_load' { return 294 }
					'clock_gettime64' { return 403 }
					'clock_settime64' { return 404 }
					'clock_adjtime64' { return 405 }
					'clock_getres_time64' { return 406 }
					'clock_nanosleep_time64' { return 407 }
					'timer_gettime64' { return 408 }
					'timer_settime64' { return 409 }
					'timerfd_gettime64' { return 410 }
					'timerfd_settime64' { return 411 }
					'utimensat_time64' { return 412 }
					'pselect6_time64' { return 413 }
					'ppoll_time64' { return 414 }
					'io_pgetevents_time64' { return 416 }
					'recvmmsg_time64' { return 417 }
					'mq_timedsend_time64' { return 418 }
					'mq_timedreceive_time64' { return 419 }
					'semtimedop_time64' { return 420 }
					'rt_sigtimedwait_time64' { return 421 }
					'futex_time64' { return 422 }
					'sched_rr_get_interval_time64' { return 423 }
					'pidfd_send_signal' { return 424 }
					'io_uring_setup' { return 425 }
					'io_uring_enter' { return 426 }
					'io_uring_register' { return 427 }
					'open_tree' { return 428 }
					'move_mount' { return 429 }
					'fsopen' { return 430 }
					'fsconfig' { return 431 }
					'fsmount' { return 432 }
					'fspick' { return 433 }
					'pidfd_open' { return 434 }
					'clone3' { return 435 }
					'close_range' { return 436 }
					'openat2' { return 437 }
					'pidfd_getfd' { return 438 }
					'faccessat2' { return 439 }
					'process_madvise' { return 440 }
					'epoll_pwait2' { return 441 }
					'mount_setattr' { return 442 }
					'quotactl_fd' { return 443 }
					'landlock_create_ruleset' { return 444 }
					'landlock_add_rule' { return 445 }
					'landlock_restrict_self' { return 446 }
					'memfd_secret' { return 447 }
					'process_mrelease' { return 448 }
					'futex_waitv' { return 449 }
					'set_mempolicy_home_node' { return 450 }
					'cachestat' { return 451 }
					'fchmodat2' { return 452 }
					'map_shadow_stack' { return 453 }
					'futex_wake' { return 454 }
					'futex_wait' { return 455 }
					'futex_requeue' { return 456 }
					'statmount' { return 457 }
					'listmount' { return 458 }
					'lsm_get_self_attr' { return 459 }
					'lsm_set_self_attr' { return 460 }
					'lsm_list_modules' { return 461 }
					'mseal' { return 462 }
					'setxattrat' { return 463 }
					'getxattrat' { return 464 }
					'listxattrat' { return 465 }
					'removexattrat' { return 466 }
					'open_tree_attr' { return 467 }
					'file_getattr' { return 468 }
					'file_setattr' { return 469 }
					'listns' { return 470 }
					'rseq_slice_yield' { return 471 }
					'syscalls' { return 472 }
					else { return error('syscall "' + sys + '" is not supported on this architecture') }
				}
			} $else {
				return error('architecture not supported for string syscall lookup')
			}
		}
	}
}
